services:
  cont-cliente:
    build: ./cliente
    volumes:
     - ./pagina-cliente/:/var/www/html/
    depends_on:
      - bd-cliente

  cont-venda:
    build: ./venda
    volumes:
     - ./pagina-venda/:/var/www/html/
    depends_on:
      - bd-venda

  api:
    image: nginx:latest
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - cont-cliente
      - cont-venda

  bd-cliente:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=cliente
      - MYSQL_USER=cliente
      - MYSQL_PASSWORD=123456
    volumes:
      - ./bd-cliente:/var/lib/mysql

  bd-venda:
    image: postgres
    environment:
      - POSTGRES_DB=venda
      - POSTGRES_USER=venda
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./bd-venda:/var/lib/postgresql/data/  

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=/phpmyadmin/
    depends_on:
      - bd-cliente

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=aluno@ic.ufmt.br
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=80
    depends_on:
      - bd-venda
